kind: pipeline
type: docker
name: publish

steps:
  - name: check
    image: node:lts-alpine
    commands:
      - ./scripts/check.sh

  - name: npm
    image: plugins/npm
    settings:
      token:
        from_secret: NPM_TOKEN

trigger:
  branch:
    - master
